source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :osx, '10.11'
inhibit_all_warnings!
#use_frameworks!

target 'ProgrammingLanguageSwiftDefinitiveGuide' do
  #pod 'GoogleAnalytics', '~> 3.1'
  #pod 'React', '0.21.0-rc'
  pod "AFNetworking"

  # Has its own copy of OCMock
  # and has access to GoogleAnalytics via the app
  # that hosts the test target

  target 'ProgrammingLanguageSwiftDefinitiveGuideTests' do
    inherit! :search_paths
    #pod 'GoogleAnalytics', '~> 3.1'
    # pod 'OCMock', '~> 2.0.1'
    #pod 'Quick', '~> 0.9.0'
    # pod 'Nimble', '3.0.0'
  end

  target 'ProgrammingLanguageSwiftDefinitiveGuideUITests' do
    inherit! :search_paths
    #pod 'GoogleAnalytics', '~> 3.1'
    # pod 'OCMock', '~> 2.0.1'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end